baseURL = 'https://christophridder.github.io/'
locale = 'da-dk'
title = 'Mayunga'
theme = "book"

[params]
BookSection = "docs"

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)'], ['$', '$']]

[markup.goldmark.extensions]
strikethrough = false

[markup.goldmark.extensions.extras.subscript]
enable = true

[markup.goldmark.extensions.extras.superscript]
enable = true

[markup.goldmark.extensions.extras.delete]
enable = true
